### ISSUE TITLE
Default process group has not been initialized

### ISSUE THREAD

**Issue by julyanghar** [winycg/CIRKD#30]
2024-10-04 22:58:25,605 semantic_segmentation INFO: Using 1 GPUs
2024-10-04 22:58:25,605 semantic_segmentation INFO: Namespace(aux=True, batch_size=16, contrast_kd_temperature=1.0, contrast_temperature=0.1, crop_size=[360, 360], data='../autodl-tmp/CamVid/CamVid', dataset='camvid', device='cuda', distributed=False, ignore_label=-1, kd_temperature=1.0, lambda_kd=1.0, lambda_memory_pixel=0.1, lambda_memory_region=0.1, lambda_minibatch_pixel=1.0, local_rank=0, log_dir='../autodl-tmp/CamVid/log', log_iter=10, lr=0.02, max_iterations=40000, momentum=0.9, no_cuda=False, num_gpus=1, pixel_contrast_size=4096, pixel_memory_size=20000, region_contrast_size=1024, region_memory_size=2000, resume=None, save_dir='../autodl-tmp/CamVid/checkpoints', save_epoch=10, save_per_iters=800, skip_val=False, start_epoch=0, student_backbone='resnet18', student_model='deeplabv3', student_pretrained='None', student_pretrained_base='../autodl-tmp/CamVid/model/resnet18-imagenet.pth', teacher_backbone='resnet101', teacher_model='deeplabv3', teacher_pretrained='../autodl-tmp/CamVid/model/deeplabv3_resnet101_camvid_best_model.pth', teacher_pretrained_base='None', val_epoch=1, val_per_iters=800, weight_decay=0.0001, workers=0)
640000 images are loaded!
101 images are loaded!
2024-10-04 22:58:33,663 semantic_segmentation INFO: Start training, Total Iterations 40000
Traceback (most recent call last):
  File "/root/CIRKD/train_cirkd.py", line 462, in <module>
    trainer.train()
  File "/root/CIRKD/train_cirkd.py", line 318, in train
    self.criterion_memory_contrast(s_outputs[-1], t_outputs[-1].detach(), targets, predict)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/CIRKD/losses/cirkd_memory.py", line 123, in forward
    s_feats = self.project_head(s_feats)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 532, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 711, in get_world_size
    return _get_group_size(group)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 263, in _get_group_size
    default_pg = _get_default_group()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 347, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

I am trying to run train_cirkd on CamVid. Now I got this error. Could you help me with that? I only use one GPU.

**Comment by julyanghar** [comment]
Here is the command I ran:
   python train_cirkd.py \
    --teacher-model deeplabv3 \
    --student-model deeplabv3 \
    --teacher-backbone resnet101 \
    --student-backbone resnet18 \
    --dataset camvid \
    --crop-size 360 360 \
    --data ../autodl-tmp/CamVid/CamVid \
    --save-dir ../autodl-tmp/CamVid/checkpoints \
    --log-dir ../autodl-tmp/CamVid/log \
    --teacher-pretrained ../autodl-tmp/CamVid/model/deeplabv3_resnet101_camvid_best_model.pth \
    --student-pretrained-base ../autodl-tmp/CamVid/model/resnet18-imagenet.pth \
    --workers 0

**Comment by winycg** [comment]
Thanks for your attention. The code is designed for multi-GPU processing. I did not test the code over one GPU.

**Comment by julyanghar** [comment]
Thank you for your reply! But I noticed that here is a param named "args.distributed". I was wondering is it possible to run it over only one GPU? This error seems to be related to the distributed settings.

**Comment by julyanghar** [comment]
Done! I added the code below to the top inside the main function.
```
    os.environ["CUDA_VISIBLE_DEVICES"] = '0'
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '5678'

    torch.distributed.init_process_group(backend='gloo',world_size=1,rank=0)
    local_rank = torch.distributed.get_rank()
    torch.cuda.set_device(local_rank)
    device = torch.device("cuda", local_rank)
``` 
Besides, I changed all nn.SyncBatchNorm to nn.BatchNorm2d so that all layers for distributed settings were disabled. Now it works.

**Comment by GiLonn** [comment]
@julyanghar Hi! I am currently using a single GPU to train the citys dataset in train_cirkd, but error messages appeared. I just saw that the error you asked is the same as mine. I modified the main function according to your method, but the error message still appeared. Could you please give me your opinion? Or we could discuss in more detail via email, thank you!
